[package]
name = "l2-sniffer-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "l2-character-daemon"
path = "src/main.rs"


[dependencies]
l2-sniffer-core.workspace = true
l2-sniffer-capture.workspace = true
l2-sniffer-protocol.workspace = true
tokio.workspace = true
clap.workspace = true
inquire.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
obfstr.workspace = true

